/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author anhhu
 */
public class thu extends javax.swing.JFrame {

    private Border roundedborder;

    /**
     * Creates new form thu
     */
    public thu() {
        initComponents();
        setTitle("Tiệm ĐỒ Ngọt");
                setIconImage();
       home1.setSVGImage("Image/shop.svg", 90, 90);
        back1.setSVGImage("Image/back.svg", 50, 50);
    }
         private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("shop.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title1 = new jPanelGradient();
        jLabel1 = new javax.swing.JLabel();
        mainchinh = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        timkiem_form = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        them_btn1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        them_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        them_btn2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        them_btn3 = new javax.swing.JButton();
        them_btn4 = new javax.swing.JButton();
        Danhmuc1 = new javax.swing.JPanel();
        back1 = new GUI.SvgImage1();
        Kmbtn1 = new javax.swing.JButton();
        Sanphambtn1 = new javax.swing.JButton();
        home1 = new GUI.SvgImage1();
        Thongkebtn1 = new javax.swing.JButton();
        Banhangbtn1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        Nhanvienbtn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 657));

        Title1.setPreferredSize(new java.awt.Dimension(0, 30));

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 232, 173));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SWEET SUPERMARKET");
        jLabel1.setMaximumSize(new java.awt.Dimension(900, 28));
        jLabel1.setMinimumSize(new java.awt.Dimension(900, 28));

        javax.swing.GroupLayout Title1Layout = new javax.swing.GroupLayout(Title1);
        Title1.setLayout(Title1Layout);
        Title1Layout.setHorizontalGroup(
            Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        Title1Layout.setVerticalGroup(
            Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        mainchinh.setBackground(new java.awt.Color(0, 255, 255));
        mainchinh.setForeground(new java.awt.Color(51, 51, 51));
        mainchinh.setPreferredSize(new java.awt.Dimension(760, 470));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Quản Lý Nhân Viên");

        timkiem_form.setBackground(new java.awt.Color(0, 255, 255));
        // Create rounded border
        int radius = 10; // Set radius of rounded corners
        Border roundedBorder = BorderFactory.createLineBorder(Color.BLACK, 1); // Set color and thickness of border
        Border compound = BorderFactory.createCompoundBorder(roundedBorder, BorderFactory.createEmptyBorder(radius, radius, radius, radius));
        timkiem_form.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(153, 255, 255))));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Tìm Kiếm");

        jLabel4.setText("ID Nhân Viên");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        them_btn1.setBackground(new java.awt.Color(38, 170, 226));
        them_btn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        them_btn1.setForeground(new java.awt.Color(255, 255, 255));
        them_btn1.setText("     Enter");
        them_btn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        them_btn1.setIconTextGap(2);
        them_btn1.setMaximumSize(new java.awt.Dimension(132, 32));
        them_btn1.setMinimumSize(new java.awt.Dimension(120, 30));
        them_btn1.setPreferredSize(new java.awt.Dimension(132, 40));
        them_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btn1ThongkebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout timkiem_formLayout = new javax.swing.GroupLayout(timkiem_form);
        timkiem_form.setLayout(timkiem_formLayout);
        timkiem_formLayout.setHorizontalGroup(
            timkiem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timkiem_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timkiem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timkiem_formLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timkiem_formLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(timkiem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timkiem_formLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timkiem_formLayout.createSequentialGroup()
                                .addComponent(them_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))))
        );
        timkiem_formLayout.setVerticalGroup(
            timkiem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timkiem_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(timkiem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(them_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("ID Nhân Viên: ");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setText("Họ Lót:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setText("Tên: ");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("CCCD:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel9.setText("Giới Tính:");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel10.setText("dd/mm/yyyy");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel11.setText("Ngày sinh:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel12.setText("Chức vụ: ");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên", "Admin" }));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel13.setText("SDT:");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        them_btn.setBackground(new java.awt.Color(38, 170, 226));
        them_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        them_btn.setForeground(new java.awt.Color(255, 255, 255));
        them_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        them_btn.setText("Thêm");
        them_btn.setMaximumSize(new java.awt.Dimension(132, 32));
        them_btn.setMinimumSize(new java.awt.Dimension(120, 30));
        them_btn.setPreferredSize(new java.awt.Dimension(132, 40));
        them_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btnThongkebtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        them_btn2.setBackground(new java.awt.Color(38, 170, 226));
        them_btn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        them_btn2.setForeground(new java.awt.Color(255, 255, 255));
        them_btn2.setText("Xóa");
        them_btn2.setMaximumSize(new java.awt.Dimension(132, 32));
        them_btn2.setMinimumSize(new java.awt.Dimension(120, 30));
        them_btn2.setPreferredSize(new java.awt.Dimension(132, 40));
        them_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btn2ThongkebtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Nhân Viên", "CCCD", "Họ&Tên", "SDT", "Tuổi", "Chức vụ", "Trạng Thái"
            }
        ));
        // Tạo TableCellRenderer để tô màu cho dòng đầu tiên
        jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // Kiểm tra nếu là dòng đầu tiên thì tô màu
                if (row == 0) {
                    c.setBackground(Color.YELLOW); // Màu vàng cho dòng đầu tiên
                } else {
                    c.setBackground(table.getBackground());
                }
                return c;
            }
        });
        jTable1.setGridColor(new java.awt.Color(102, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(102, 255, 255));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("ID Nhân Viên");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("CCCD");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Họ&Tên");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("SDT");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Tuổi");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Chức vụ");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Trạng Thái");
        }

        them_btn3.setBackground(new java.awt.Color(38, 170, 226));
        them_btn3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        them_btn3.setForeground(new java.awt.Color(255, 255, 255));
        them_btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        them_btn3.setText("Hoàn Tác");
        them_btn3.setMaximumSize(new java.awt.Dimension(132, 32));
        them_btn3.setMinimumSize(new java.awt.Dimension(120, 30));
        them_btn3.setPreferredSize(new java.awt.Dimension(132, 40));
        them_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btn3ThongkebtnActionPerformed(evt);
            }
        });

        them_btn4.setBackground(new java.awt.Color(38, 170, 226));
        them_btn4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        them_btn4.setForeground(new java.awt.Color(255, 255, 255));
        them_btn4.setText("Sửa");
        them_btn4.setMaximumSize(new java.awt.Dimension(132, 32));
        them_btn4.setMinimumSize(new java.awt.Dimension(120, 30));
        them_btn4.setPreferredSize(new java.awt.Dimension(132, 40));
        them_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btn4ThongkebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainchinhLayout = new javax.swing.GroupLayout(mainchinh);
        mainchinh.setLayout(mainchinhLayout);
        mainchinhLayout.setHorizontalGroup(
            mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainchinhLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainchinhLayout.createSequentialGroup()
                        .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainchinhLayout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainchinhLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(mainchinhLayout.createSequentialGroup()
                            .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainchinhLayout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56)
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mainchinhLayout.createSequentialGroup()
                                    .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(timkiem_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainchinhLayout.createSequentialGroup()
                            .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainchinhLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mainchinhLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(mainchinhLayout.createSequentialGroup()
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel10)
                                    .addGap(137, 137, 137))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainchinhLayout.createSequentialGroup()
                                    .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(them_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(them_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40)
                                    .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(them_btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                        .addComponent(them_btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        mainchinhLayout.setVerticalGroup(
            mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainchinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainchinhLayout.createSequentialGroup()
                        .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(timkiem_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        Danhmuc1.setBackground(new java.awt.Color(167, 255, 244));
        Danhmuc1.setAlignmentX(0.0F);
        Danhmuc1.setAlignmentY(0.0F);
        Danhmuc1.setPreferredSize(new java.awt.Dimension(140, 470));

        Kmbtn1.setBackground(new java.awt.Color(38, 170, 226));
        Kmbtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Kmbtn1.setForeground(new java.awt.Color(255, 255, 255));
        Kmbtn1.setText("Khuyến Mãi");
        Kmbtn1.setPreferredSize(new java.awt.Dimension(130, 40));
        Kmbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kmbtn1KmbtnActionPerformed(evt);
            }
        });

        Sanphambtn1.setBackground(new java.awt.Color(38, 170, 226));
        Sanphambtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Sanphambtn1.setForeground(new java.awt.Color(255, 255, 255));
        Sanphambtn1.setText("Sản Phẩm");
        Sanphambtn1.setMaximumSize(new java.awt.Dimension(132, 32));
        Sanphambtn1.setPreferredSize(new java.awt.Dimension(132, 40));
        Sanphambtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sanphambtn1MouseClicked(evt);
            }
        });
        Sanphambtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sanphambtn1SanphambtnActionPerformed(evt);
            }
        });

        home1.setPreferredSize(new java.awt.Dimension(120, 120));

        Thongkebtn1.setBackground(new java.awt.Color(38, 170, 226));
        Thongkebtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Thongkebtn1.setForeground(new java.awt.Color(255, 255, 255));
        Thongkebtn1.setText("Thống Kê");
        Thongkebtn1.setMaximumSize(new java.awt.Dimension(132, 32));
        Thongkebtn1.setMinimumSize(new java.awt.Dimension(120, 30));
        Thongkebtn1.setPreferredSize(new java.awt.Dimension(132, 40));
        Thongkebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thongkebtn1ThongkebtnActionPerformed(evt);
            }
        });

        Banhangbtn1.setBackground(new java.awt.Color(38, 170, 226));
        Banhangbtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Banhangbtn1.setForeground(new java.awt.Color(255, 255, 255));
        Banhangbtn1.setText("Bán Hàng");
        Banhangbtn1.setMaximumSize(new java.awt.Dimension(32, 32));
        Banhangbtn1.setPreferredSize(new java.awt.Dimension(132, 40));
        Banhangbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Banhangbtn1BanhangbtnMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Banhangbtn1BanhangbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Banhangbtn1BanhangbtnMouseReleased(evt);
            }
        });
        Banhangbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Banhangbtn1BanhangbtnActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        Nhanvienbtn2.setBackground(new java.awt.Color(38, 170, 226));
        Nhanvienbtn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Nhanvienbtn2.setForeground(new java.awt.Color(255, 255, 255));
        Nhanvienbtn2.setText("Nhân Viên");
        Nhanvienbtn2.setMaximumSize(new java.awt.Dimension(32, 32));
        Nhanvienbtn2.setPreferredSize(new java.awt.Dimension(132, 40));
        Nhanvienbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nhanvienbtn2Nhanvienbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Danhmuc1Layout = new javax.swing.GroupLayout(Danhmuc1);
        Danhmuc1.setLayout(Danhmuc1Layout);
        Danhmuc1Layout.setHorizontalGroup(
            Danhmuc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Danhmuc1Layout.createSequentialGroup()
                .addGroup(Danhmuc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Danhmuc1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Danhmuc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Sanphambtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Banhangbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Thongkebtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nhanvienbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Kmbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Danhmuc1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(Danhmuc1Layout.createSequentialGroup()
                .addGroup(Danhmuc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Danhmuc1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(home1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Danhmuc1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        Danhmuc1Layout.setVerticalGroup(
            Danhmuc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Danhmuc1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(home1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Banhangbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Sanphambtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Kmbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Nhanvienbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Thongkebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Danhmuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainchinh, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Danhmuc1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addComponent(mainchinh, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void Kmbtn1KmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kmbtn1KmbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kmbtn1KmbtnActionPerformed

    private void Sanphambtn1SanphambtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sanphambtn1SanphambtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sanphambtn1SanphambtnActionPerformed

    private void Thongkebtn1ThongkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thongkebtn1ThongkebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Thongkebtn1ThongkebtnActionPerformed

    private void Banhangbtn1BanhangbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Banhangbtn1BanhangbtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Banhangbtn1BanhangbtnMouseEntered

    private void Banhangbtn1BanhangbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Banhangbtn1BanhangbtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Banhangbtn1BanhangbtnMousePressed

    private void Banhangbtn1BanhangbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Banhangbtn1BanhangbtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Banhangbtn1BanhangbtnMouseReleased

    private void Banhangbtn1BanhangbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Banhangbtn1BanhangbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Banhangbtn1BanhangbtnActionPerformed

    private void Nhanvienbtn2Nhanvienbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nhanvienbtn2Nhanvienbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nhanvienbtn2Nhanvienbtn1ActionPerformed

    private void them_btn1ThongkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btn1ThongkebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_them_btn1ThongkebtnActionPerformed

    private void them_btnThongkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btnThongkebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_them_btnThongkebtnActionPerformed

    private void them_btn2ThongkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btn2ThongkebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_them_btn2ThongkebtnActionPerformed

    private void them_btn3ThongkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btn3ThongkebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_them_btn3ThongkebtnActionPerformed

    private void them_btn4ThongkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btn4ThongkebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_them_btn4ThongkebtnActionPerformed

    private void Sanphambtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sanphambtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Sanphambtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Banhangbtn1;
    private javax.swing.JPanel Danhmuc1;
    private javax.swing.JButton Kmbtn1;
    private javax.swing.JButton Nhanvienbtn2;
    private javax.swing.JButton Sanphambtn1;
    private javax.swing.JButton Thongkebtn1;
    private javax.swing.JPanel Title1;
    private GUI.SvgImage1 back1;
    private GUI.SvgImage1 home1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel mainchinh;
    private javax.swing.JButton them_btn;
    private javax.swing.JButton them_btn1;
    private javax.swing.JButton them_btn2;
    private javax.swing.JButton them_btn3;
    private javax.swing.JButton them_btn4;
    private javax.swing.JPanel timkiem_form;
    // End of variables declaration//GEN-END:variables
}
